<?php

return [
    'states' => [
        [
            'name' => 'México',
            'children' => [
                ['name' => 'Villa de Allende', 'children' => [
                    ['name' => 'Ampliación Ejido de San Ildefonso'],
                    ['name' => 'Barrio Chiquichuca'],
                    ['name' => 'Barrio de San Juan'],
                    ['name' => 'Barrio de San Miguel'],
                    ['name' => 'Barrio de Santa Cruz, San Jerónimo Totoltepec'],
                    ['name' => 'Barrio de Santiago'],
                    ['name' => 'Barrio el Boncho'],
                    ['name' => 'Barrio el Salto'],
                    ['name' => 'Barrio la Joya'],
                    ['name' => 'Barrio los Cedros'],
                    ['name' => 'Barrio los Pozos'],
                    ['name' => 'Barrio los Tules'],
                    ['name' => 'Barrio Santa Cruz'],
                    ['name' => 'Batán Chico'],
                    ['name' => 'Bosencheve'],
                    ['name' => 'Buenavista 23'],
                    ['name' => 'Cabecera de Indígenas'],
                    ['name' => 'Casa Blanca'],
                    ['name' => 'Cerro de Guadalupe'],
                    ['name' => 'Cuesta del Carmen'],
                    ['name' => 'Ejido de San Martín'],
                    ['name' => 'Ejido Sabana de San Jerónimo'],
                    ['name' => 'El Aventurero'],
                    ['name' => 'El Chirimoyo'],
                    ['name' => 'El Cinco'],
                    ['name' => 'El Jacal'],
                    ['name' => 'El Potrero'],
                    ['name' => 'El Puerto Lengua de Vaca'],
                    ['name' => 'Filiberto Gómez'],
                    ['name' => 'La Peña'],
                    ['name' => 'La Piedra'],
                    ['name' => 'Las Casitas'],
                    ['name' => 'Las Dalias'],
                    ['name' => 'Loma Chica'],
                    ['name' => 'Loma de Juárez'],
                    ['name' => 'Loma de San Pablo'],
                    ['name' => 'Los Berros'],
                    ['name' => 'Los Hoyos'],
                    ['name' => 'Macia'],
                    ['name' => 'Manzana de Cashte'],
                    ['name' => 'Manzana de Chichicaishle'],
                    ['name' => 'Manzana del Puerto'],
                    ['name' => 'Manzana la Pera'],
                    ['name' => 'Manzana los Colchones'],
                    ['name' => 'Mesa Chica'],
                    ['name' => 'Mesas de San Jerónimo'],
                    ['name' => 'Mesas de San Juan Buenavista'],
                    ['name' => 'Mesas de San Martín'],
                    ['name' => 'Mesas de Zacango'],
                    ['name' => 'Mesas del Clarín'],
                    ['name' => 'Monte Alto'],
                    ['name' => 'Rancho Morelos'],
                    ['name' => 'Sabana de la Peña'],
                    ['name' => 'Sabana de San Jerónimo'],
                    ['name' => 'Sabana de Taborda 1ra. Sección'],
                    ['name' => 'Sabana de Taborda 2da. Sección'],
                    ['name' => 'Sabana del Madroño'],
                    ['name' => 'Sabana del Refugio'],
                    ['name' => 'Sabana del Rosario'],
                    ['name' => 'Salitre del Cerro'],
                    ['name' => 'San Agustín Berros el Salto'],
                    ['name' => 'San Cayetano'],
                    ['name' => 'San Felipe Santiago'],
                    ['name' => 'San Francisco de Asís'],
                    ['name' => 'San Ildefonso'],
                    ['name' => 'San Isidro'],
                    ['name' => 'San Jerónimo Totoltepec'],
                    ['name' => 'San José Villa de Allende'],
                    ['name' => 'San Juan Buenavista'],
                    ['name' => 'San Miguel la Máquina'],
                    ['name' => 'San Pablo Malacatepec'],
                    ['name' => 'Santa María de las Delicias'],
                    ['name' => 'Santa Teresa'],
                    ['name' => 'Soledad del Salitre'],
                    ['name' => 'Vare Chiquichuca'],
                ]],
                ['name' => 'Villa victoria', 'children' => [
                    ['name' => 'Agua Grande'],
                    ['name' => 'Barrio de Centro del Cerrillo'],
                    ['name' => 'Barrio de Puentecillas'],
                    ['name' => 'Barrio de San Isidro'],
                ]]
            ]
        ]
    ]
];